import './globals.css'
import type { Metadata } from 'next'
import { Comic_Neue } from 'next/font/google'
import NavMenu from './NavMenu'
import AuthProvider from './AuthProvider'

const comic = Comic_Neue({ subsets: ['latin'], weight: ['300', '400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={comic.className}>
          <NavMenu />
          <div className='mt-[65px] p-12'>
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  )
}
